apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-eks-cluster
  region: ap-south-1
  version: "1.29"

nodeGroups:
  - name: demo-node-group
    instanceType: t2.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    ssh:
      allow: true
    labels:
      role: worker
