const Order = require("../models/Order");

/**
 * @desc    Create a new order
 * @route   POST /api/orders
 * @access  Public
 */
const createOrder = async (req, res) => {
  try {
    const {
      customerName,
      customerEmail,
      customerPhone,
      deliveryAddress,
      items,
      totalPrice,
    } = req.body;

    // Validate required fields
    if (!customerName || !customerEmail || !customerPhone || !deliveryAddress) {
      return res.status(400).json({ message: "All customer details are required" });
    }

    if (!items || items.length === 0) {
      return res.status(400).json({ message: "Order must contain at least one item" });
    }

    // Create order (orderNo is auto-generated by pre-save hook)
    const order = new Order({
      customerName,
      customerEmail,
      customerPhone,
      deliveryAddress,
      items,
      totalPrice,
    });

    const savedOrder = await order.save();
    res.status(201).json(savedOrder);
  } catch (error) {
    console.error("Create order error:", error);
    res.status(500).json({ message: "Server error" });
  }
};

/**
 * @desc    Get all orders (with optional search by orderNo)
 * @route   GET /api/orders
 * @access  Admin
 */
const getOrders = async (req, res) => {
  try {
    const { search, status } = req.query;
    let query = {};

    // Search by order number
    if (search) {
      query.orderNo = { $regex: search, $options: "i" };
    }

    // Filter by status
    if (status && status !== "All") {
      query.orderStatus = status;
    }

    const orders = await Order.find(query).sort({ createdAt: -1 });
    res.json(orders);
  } catch (error) {
    console.error("Get orders error:", error);
    res.status(500).json({ message: "Server error" });
  }
};

/**
 * @desc    Get single order by order number
 * @route   GET /api/orders/:orderNo
 * @access  Admin
 */
const getOrderByNo = async (req, res) => {
  try {
    const order = await Order.findOne({ orderNo: req.params.orderNo });
    if (!order) {
      return res.status(404).json({ message: "Order not found" });
    }
    res.json(order);
  } catch (error) {
    console.error("Get order error:", error);
    res.status(500).json({ message: "Server error" });
  }
};

/**
 * @desc    Update order status
 * @route   PUT /api/orders/:id
 * @access  Admin
 */
const updateOrder = async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);
    if (!order) {
      return res.status(404).json({ message: "Order not found" });
    }

    const { orderStatus, paymentStatus } = req.body;

    if (orderStatus) order.orderStatus = orderStatus;
    if (paymentStatus) order.paymentStatus = paymentStatus;

    const updatedOrder = await order.save();
    res.json(updatedOrder);
  } catch (error) {
    console.error("Update order error:", error);
    res.status(500).json({ message: "Server error" });
  }
};

/**
 * @desc    Mark order as paid (simulated payment confirmation)
 * @route   PUT /api/orders/:id/pay
 * @access  Public
 */
const markOrderPaid = async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);
    if (!order) {
      return res.status(404).json({ message: "Order not found" });
    }

    order.paymentStatus = "Paid";
    const updatedOrder = await order.save();
    res.json(updatedOrder);
  } catch (error) {
    console.error("Mark paid error:", error);
    res.status(500).json({ message: "Server error" });
  }
};

module.exports = {
  createOrder,
  getOrders,
  getOrderByNo,
  updateOrder,
  markOrderPaid,
};
